version: '3.6'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 5454:8080

  db:
    image: 'postgres:13'
    container_name: db
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pager_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
